apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: workerservice-deployment
spec:
  selector:
    matchLabels:
      app: workerservice-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: workerservice-pod
    spec:
      containers:
      - name: ws-container
        image: crworkerservice.azurecr.io/workerservice:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: dr-secrets